### ISSUE TITLE
A lot of unnecessary TCP reconnections

### ISSUE THREAD

**Issue by hessu** [Guru-RF/LoraAPRSGateway#1]
https://github.com/Guru-RF/LoraAPRSGateway/blob/d9ff2651c9a74591801b72f998b2bb71b3c973bc/code.py#L97

Despite the name of the "udpPost" function, it opens a TCP connection, just to post a single packet, and does a reconnection and new login for each and every packet.

Please keep a single persistent connection open and use it to post all packets as long as the connection is maintaned successfully. This reduces the load on the APRS-IS servers, and their logging data, a lot.

**Comment by ure** [comment]
Thx for the feedback, I was testing the UDP only feed but that didn't work ... i'll investigate further ... and adopt accordingly

**Comment by ure** [comment]
tested the UDP only port (8080) but that does not use the same TNC handling as the TCP version, that would have been nice since that only requires a single UDP packet to auth and send the data ... i adopted the tcp version to reuse the socket and only auth when recreated when list or any other issue
